# Generated by Django 3.1 on 2020-08-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_test1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
